# Generated by Django 4.2.7 on 2025-04-13 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_email_verified_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favorite_genres',
        ),
    ]
