# Generated by Django 4.2.7 on 2025-04-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='poster_url',
            field=models.URLField(blank=True, help_text='URL to episode poster image', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='backdrop_url',
            field=models.URLField(blank=True, help_text='URL to backdrop image if not uploading', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='poster_url',
            field=models.URLField(blank=True, help_text='URL to poster image if not uploading', null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL to video (YouTube, Vimeo, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL to video (YouTube, Vimeo, etc.)', null=True),
        ),
    ]
