# Generated by Django 4.2.7 on 2025-04-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_episode_poster_url_video_backdrop_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='video',
            name='backdrop',
        ),
        migrations.RemoveField(
            model_name='video',
            name='backdrop_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='director',
        ),
        migrations.RemoveField(
            model_name='video',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='video',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='video',
            name='release_year',
        ),
    ]
